# Generated by Django 5.0.6 on 2024-07-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('fname', models.CharField(max_length=25)),
                ('mobile', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=25)),
                ('fnumber', models.CharField(max_length=11)),
                ('dobe', models.CharField(max_length=20)),
                ('sclass', models.CharField(max_length=5)),
                ('sfee', models.CharField(max_length=10)),
                ('balance', models.IntegerField(max_length=25)),
                ('pic', models.FileField(upload_to='')),
                ('address', models.TextField()),
            ],
        ),
    ]
