# Generated by Django 5.0.6 on 2024-07-06 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_student_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('roomno', models.CharField(max_length=20)),
                ('seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LoginUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=10)),
                ('usertype', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAttendance',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('studentid', models.CharField(max_length=10)),
                ('date', models.CharField(max_length=10)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('classid', models.CharField(max_length=20)),
                ('teacherid', models.CharField(max_length=20)),
                ('book', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('address', models.TextField()),
                ('qualification', models.CharField(max_length=40)),
                ('experience', models.CharField(max_length=40)),
                ('tclass', models.CharField(max_length=20)),
                ('tsalary', models.IntegerField()),
                ('pic', models.FileField(upload_to='')),
                ('created', models.DateTimeField()),
            ],
        ),
    ]
