# Generated by Django 5.0.6 on 2024-07-08 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_class_loginuser_studentattendance_subjects_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='dobe',
            new_name='dob',
        ),
    ]
