# Generated by Django 5.0.6 on 2024-07-08 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_dobe_student_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
    ]
