# Generated by Django 5.0.6 on 2024-07-10 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_student_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(upload_to='media'),
        ),
    ]
