# Generated by Django 5.0.6 on 2024-07-10 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_teacher_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
