# Generated by Django 5.0.6 on 2024-07-12 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_teacher_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentattendance',
            name='sclass',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(upload_to=''),
        ),
    ]
