# Generated by Django 5.0.6 on 2024-07-23 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_enquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('notice', models.TextField()),
                ('created', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
